### PR TITLE
Switch to github pages provider

### PR DESCRIPTION
**Pull request by zekth**
Use the github pages built in provider from travis instead of deploy script.

ref: https://docs.travis-ci.com/user/deployment#deploying-to-multiple-providers
ref: https://docs.travis-ci.com/user/deployment/pages/

### CODE REVIEW

**Comment by zekth** [comment]
Seems like the changes are not related to the issue in the CI

**Comment by haata** [comment]
Once I get into the GitHub Actions beta I'll see about moving there (there have been some issues integrating Travis with GitHub secrets).

**Comment by zekth** [comment]
> Once I get into the GitHub Actions beta I'll see about moving there (there have been some issues integrating Travis with GitHub secrets).

I have also setup a github actions for this kind of workflow. You want me to share it? Working perfectly with secrets

**Comment by haata** [comment]
Just got into the github actions beta. Definitely interested in what you've done.

I've been fighting with pycapnp + SSL lately (hence the lack of commits), but I think I almost have a solution.

**Comment by zekth** [comment]
Here it is: https://github.com/zekth/keycap-ruler/blob/master/.github/workflows/nodejs.yml

**Comment by haata** [comment]
I've added the GitHub Action (https://hid-io.github.io/hid-io/hid_io/). Thanks!

**Pull request closed without merging**
